### ISSUE TITLE
Write a section introduction for "Growing Contributors"

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#81]
Fine name in repo: growing_contribuots_section.adoc

Does not need a Conclusion

Can cover the arc from user to contributor, especially for people who jump right to this chapter, trying to skip fundamentals. This introduction should point back to the fundamentals.

**Comment by mbbroberg** [comment]
Ideas that comet o mind: 

- Following effective practices to do so (I've outlined some here https://mbbroberg.fun/talks/#open-source-101)
- Having maintainers who practice inclusive contribution (Ex. [Homebrew](https://docs.brew.sh/New-Maintainer-Checklist))

Question for you @quaid: would this include what might be called "marketing" of the project like in [Karl Fogel's guide](https://producingoss.com/en/marketing.html)?

**Comment by quaid** [comment]
> Ideas that comet o mind:
> 
>     * Following effective practices to do so (I've outlined some here https://mbbroberg.fun/talks/#open-source-101)
> 
>     * Having maintainers who practice inclusive contribution (Ex. [Homebrew](https://docs.brew.sh/New-Maintainer-Checklist))

Right, and we have to keep the recursive aspect in mind--the section intro is also defined by the chapters within that section, and by the desire to have it stand alone reasonably well.

So like you linked, we'll want to have a compressed narrative of what transpired "earlier" in the guide, like a recap at the start of an episodic TV show. It will be good to have some new ways or links at that point, so there is new value for people who are reading the sections/chapters sequentially.

> Question for you @quaid: would this include what might be called "marketing" of the project like in [Karl Fogel's guide](https://producingoss.com/en/marketing.html)?

Yes and, meaning the methodology is for marketing to have several facets. You want to make your project's artifacts wildly, amazingly useful to your user base; this applies if it's a general purpose software thing or a complex developer tool, they are all your users. I would say that is what Karl's marketing section focuses on, unsurprisingly--it's the hard job and the source of the most rewards.

The participants also get marketing focus and a plan, I reckon--you want them to know and be able to deliver your project's key messages and helpfulness via their enthusiasm. The contributors, by the time we get there need far less marketing and far more enablement.

**Comment by shaunix** [comment]
Copy edit notes:

- Second paragraph: "responding and enabling someone outside of that community" feels a touch weird because my brain wants to treat "responding" as something that also applies to "someone". Reading it a second time, I see it can be read as "(responding) and (enabling someone)", but initially my brain went to "(responding and enabling) someone" and really wanted a "to" in there. Do with that information what you want.

- Second paragraph: Assuming final sentence fragment is intentional for emphasis (fine by me), but it does still need a period.

- Third paragraph: "it's" -> "its"

- First list, second bullet: "provides" -> "provide"

- First list, third and sixth bullets: You use "towards" then "toward". I have zero opinion on which one of these you use, but pick one. You do use "towards" in paragraph 2.

- First list, eighth bullet: "meaning" should probably be plural I think.

- First list, ninth bullet: "importance and techniques for self-care" parses as "importance for self-care and techniques for self-care". Maybe "importance of and techniques for self-care" ?

- Second list, final bullet: "savor" -> "savoring". Incidentally, I love this sentence.

**Comment by quaid** [comment]
100% spot on edits, insights, and catches, as usual. Fixed in https://github.com/theopensourceway/guidebook/commit/10eba8c9b0176feb9c2ae03594209fabf708f289.
