### ISSUE TITLE
Write a section introduction for "Attracting Users"

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#83]
Filename in repo: attracting_users_section.adoc

Does not need a Conclusion

**Comment by mbbroberg** [comment]
This might be best aligned with my interests. I've been researching how to market projects and find interest in all the noise of open source these days. I'm also a big fan of [Karl Fogel's guide](https://producingoss.com/en/marketing.html) and can represent the ideas based on the project's archetypes (based on [Mozilla's research](https://blog.mozilla.org/wp-content/uploads/2018/05/MZOTS_OS_Archetypes_report_ext_scr.pdf)).

**Comment by semioticrobotic** [comment]
That's great, @mbbroberg!

This issue is ideally for the introduction to the "Attracting Users" section. In _The Open Source Way_, a "section" a collection of chapters. Can you identify [a chapter in the section](https://github.com/theopensourceway/guidebook/blob/master/OUTLINE.adoc) that might benefit from your contribution? Or maybe you'd suggest something that's not already there?
