### ISSUE TITLE
Write a section introduction for "Measuring Success"

### ISSUE THREAD

**Issue by quaid** [theopensourceway/guidebook#85]
File name in repo: measuring_success_section.adoc

Does not need a Conclusion

**Comment by mbbroberg** [comment]
I'd love to edit the editor on this one or co-author if you'd like @bproffitt

**Comment by junaruga** [comment]
I was checking the existing issue tickets about this subject.

I think the current ["Open Source Way" document](https://www.theopensourceway.org/preview-1.99-book.html) is outstanding. Thank you for providing it! However while I see 2.2 Marketing positioning, I was not able to find the section how to measure the thriving of a project.

I want to know a marketing activity that we did is good or bad.  and want to know which part in a website or documents in GitHub do we need to improve.

* Website: I want to measure the number of page view (PV), unique user (UU), conversion rate between point A and B, A/B split test and etc. Google Analytics is the well-known tool. But is it suitable for a open source project? People working on the open source project might prefer open data rather than exclusive data.
* GitHub repositories: I want to measure the favourites, forks, commits regularly.

What do you think of using this kind of analysis tools for a open source project? Do you have some recommendations about the tools?
Thank you.

**Comment by junaruga** [comment]
One more thing. What I want to measure is about people's retention and acquisition.

* Retention: how people engage continuously?
* Acquisition: how people are involved by some activities to acquire people?

**Comment by semioticrobotic** [comment]
Thanks for requesting this, @junaruga. I recommend getting started with [Chapter 7](https://www.theopensourceway.org/preview-1.99-book.html#_understanding_community_metrics) of _The Open Source Way_, which is about measuring project success, establishing success metrics, and setting metrics-conscious goals. That chapter offers a few suggested pathways for getting started. Moreover, don't forget the [CHAOSS project](https://chaoss.community/)!

**Comment by junaruga** [comment]
Wow, @semioticrobotic thanks for sharing the info! I will take a look at it!

**Comment by shaunix** [comment]
Copy edit notes:

- Very minor nitpick you can ignore: in the last full paragraph, a sentence starts with "Now, though, one can easily dive". Everything so far has been in casual second person, so I don't see the need to pull out "one".

- The final list doesn't read right, because it's missing "you". Except on the last bullet point. Either put "you" after the intro text "useful for you if" and remove it from the last bullet, or put "You" at the beginning of each bullet. I prefer the latter.

**Comment by shaunix** [comment]
On my point above, I just noticed that "Growing Contributors" puts "You" at the beginning of each bullet, so let's do that.

**Comment by quaid** [comment]
> On my point above, I just noticed that "Growing Contributors" puts "You" at the beginning of each bullet, so let's do that.

Yes, you are correct, that is the format, I didn't notice it on my edit, good catch.

Both edits are now fixed in https://github.com/theopensourceway/guidebook/commit/22290f8055ab4dd3fce236a9553022976eb49348.
